# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: ArcGIS Open Data
email: opendata@esri.com
description: > # this means to ignore newlines until "baseurl:"
  Building relationships with data.
baseurl: "/opendata" # the subpath of your site, e.g. /blog
url: "http://opendata.arcgis.com" # the base hostname & protocol for your site
twitter_username: esridc
github_username:  esridc

# Build settings
markdown: kramdown
